name: Daily Cypress Tests

on: [push]

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Manila
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Ensure this is set in your GitHub repo secrets

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v3
      with:
        record: true # Enables recording test results on Cypress Cloud
        # Add additional configurations if needed
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
