name: Daily Cypress Tests

on: [push]

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Manila
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v3
      with:
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_STAGING_APP_ENV: ${{ secrets.CYPRESS_STAGING_APP_ENV }}
        CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
        CYPRESS_STAGING_BILLING_AND_PLANS_ENDPOINT: ${{ secrets.CYPRESS_STAGING_BILLING_AND_PLANS_ENDPOINT }}
        CYPRESS_STAGING_FORGOTPW_AUTH_TOKEN: ${{ secrets.CYPRESS_STAGING_FORGOTPW_AUTH_TOKEN }}
        CYPRESS_STAGING_MAILINATOR_BEARER_TOKEN: ${{ secrets.CYPRESS_STAGING_MAILINATOR_BEARER_TOKEN }}
        CYPRESS_STAGING_PAYMENT_METHOD_ENDPOINT: ${{ secrets.CYPRESS_STAGING_PAYMENT_METHOD_ENDPOINT }}
        CYPRESS_STAGING_PERSONAL_ACCOUNT: ${{ secrets.CYPRESS_STAGING_PERSONAL_ACCOUNT }}
        CYPRESS_STAGING_PERSONAL_PASSWORD: ${{ secrets.CYPRESS_STAGING_PERSONAL_PASSWORD }}
        CYPRESS_STAGING_TEST_ADMIN_ACCOUNT: ${{ secrets.CYPRESS_STAGING_TEST_ADMIN_ACCOUNT }}
        CYPRESS_STAGING_TEST_ADMIN_EXPIRED_MONTHLY_WFM: ${{ secrets.CYPRESS_STAGING_TEST_ADMIN_EXPIRED_MONTHLY_WFM }}
        CYPRESS_STAGING_TEST_MANAGER_ACCOUNT: ${{ secrets.CYPRESS_STAGING_TEST_MANAGER_ACCOUNT }}
        CYPRESS_STAGING_TEST_WORKER_ACCOUNT: ${{ secrets.CYPRESS_STAGING_TEST_WORKER_ACCOUNT }}
