name: Daily Cypress Tests

on:
  schedule:
    - cron: '20 06 * * *'
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Manila
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v3
      with:
        run: npm run cypress:run
        wait-on: 'http://localhost:3000'
        record: true
        parallel: true
        config: baseUrl=http://localhost:3000
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
